[package]
name = "mcp-protocol"
version = "0.2.3"
edition = "2021"
description = "Protocol definitions for the Model Context Protocol (MCP)"
license = "MIT"
repository = "https://github.com/colinrozzi/rust-mcp"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
