[package]
name = "resource-server"
version = "0.1.0"
edition = "2021"

[dependencies]
modelcontextprotocol-server = { path = "../../mcp-server" }
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
